language: node_js
node_js:
  - "14"
  - "12"
  - "10"

install: npm install
script: npm test

jobs:
  include:
    - env: LNURL_STORE_BACKEND=knex LNURL_STORE_CONFIG='{"client":"sqlite3","connection":{"filename":"./test/tmp/db.sqlite3"},"useNullAsDefault":true}'
      before_script: npm install knex@0.95.x sqlite3@5.0.x
    - env: LNURL_STORE_BACKEND=knex LNURL_STORE_CONFIG='{"client":"mysql","connection":{"host":"127.0.0.1","user":"root","password":"","database":"lnurl_test"}}'
      services: mysql
      before_install: "mysql -e 'drop database if exists lnurl_test; create database lnurl_test;'"
      before_script: npm install knex@0.95.x mysql@2.18.x
    - env: LNURL_STORE_BACKEND=knex LNURL_STORE_CONFIG='{"client":"postgres","connection":{"host":"127.0.0.1","user":"postgres","password":"","database":"lnurl_test"}}'
      services: postgresql
      before_install: "psql -c 'create database lnurl_test;' -U postgres"
      before_script: npm install knex@0.95.x pg@8.6.x
